id = "truly-zen-theme"
name = "Truly Zen"
version = "1.0.0"
schema_version = 1
authors = ["Abhinav Sarkar"]
description = "A zed editor theme for total concentration."
repository = "https://github.com/abhinaaaavvv/truly-zen-theme"
themes = ["themes/truly-zen.json"]
